version: "3"
services:
  rails:
    image: quay.io/forem/forem:latest
    container_name: forem_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://forem:forem@db:5432/forem_db
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: dev.alpelectronix.com
      SECRET_KEY_BASE: "s9485kfjskha-*09487bv+#2>|"
      APP_PROTOCOL: "https://"
    volumes:
      - .:/opt/apps/forem:z
    # entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "2700s"]
    command: [ "bash", "-c", "./scripts/entrypoint.sh bootstrap && bundle exec rails server -b 0.0.0.0 -p 3000"]

  seed:
    image: quay.io/forem/forem:latest
    container_name: forem_seed
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: production
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/forem_db
    volumes:
      - .:/opt/apps/forem:z
    # entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "http://rails:3000", "-timeout", "300s"]
    command: ["bundle", "exec", "rake","db:seed"]

  sidekiq:
    image: quay.io/forem/forem:latest
    container_name: forem_sidekiq
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: production
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/forem_db
    volumes:
      - .:/opt/apps/forem:z
    # entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "http://rails:3000", "-timeout", "300s"]
    command: ["bundle", "exec", "sidekiq","-c","2"]

  db:
    image: postgres:15-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: forem_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:Z

  redis:
    image: redis:6.2-alpine
    container_name: forem_redis
    ports:
      - "6380:6379"

volumes:
  db_data:
